version: "3.9"
services:
    mock-database:
        image: saheru/grpc-benchmark
        hostname: mock-database
        ports:
            - "20011:10011"
        entrypoint:
            ["taskset", "1", "/app/cmake/build/mockDatabase", "1", "${W_MOCK}", "${t_MOCK}", "${s_MOCK}"]
        volumes:
          - ./container_files/${STATSDIR}/:/app/stats_files:rw
        stop_signal: SIGINT

    sanitization-service:
        image: saheru/grpc-benchmark
        hostname: sanitization-service
        ports:
            - "20013:10013"
        entrypoint:
            ["taskset", "3", "/app/cmake/build/sanitizationService", "${W_SANIT}", "${t_SANIT}", "${s_SANIT}"]
        depends_on:
            - mock-database
        volumes:
          - ./container_files/${STATSDIR}/:/app/stats_files:rw
        stop_signal: SIGINT

    message-service:
        image: saheru/grpc-benchmark
        hostname: message-service
        ports:
            - "20012:10012"
        entrypoint:
            ["taskset", "5", "/app/cmake/build/messageService", "${W_MSG}", "${t_MSG}", "${s_MSG}"]
        depends_on:
            - mock-database
            - sanitization-service
        volumes:
          - ./container_files/${STATSDIR}/:/app/stats_files:rw
        stop_signal: SIGINT

    client:
        image: saheru/grpc-benchmark
        hostname: client
        # restart: always
        entrypoint:
            ["/app/cmake/build/clientAsync", "1", "${N}", "${t_DELAY}", "${s_DELAY}", "${P}", "${SEED}"]
        depends_on:
            - message-service
        volumes:
          - ./container_files/${STATSDIR}/:/app/stats_files:rw
        stop_signal: SIGINT
