version: "3.9"
services:
    mock-database:
        image: saheru/grpc-benchmark
        hostname: mock-database
        ports:
            - 20001:10001
        entrypoint:
            ["/app/cmake/build/mockDatabaseAsync", "1", "32", "100000"] #Last argument is delay of mock database, in microseconds
        volumes:
          - ./stats_files:/app/stats_files:rw
        stop_signal: SIGINT

    sanitization-service:
        image: saheru/grpc-benchmark
        hostname: sanitization-service
        ports:
            - 20003:10003
        entrypoint:
            ["/app/cmake/build/sanitizationServiceAsync", "1", "32"]
        depends_on:
            - mock-database
        volumes:
          - ./stats_files:/app/stats_files:rw
        stop_signal: SIGINT

    message-service:
        image: saheru/grpc-benchmark
        hostname: message-service
        ports:
            - 20002:10002
        entrypoint:
            ["/app/cmake/build/messageServiceAsync", "1", "32"]
        depends_on:
            - mock-database
            - sanitization-service
        volumes:
          - ./stats_files:/app/stats_files:rw
        stop_signal: SIGINT

    client:
        image: saheru/grpc-benchmark
        hostname: client
        # restart: always
        entrypoint:
            #Before the last argument is delay between query, in microseconds
            #The last argument is the factor modifiying the waiting time at each iterations
            ["/app/cmake/build/clientAsync", "100", "TestUser", "Test Message", "100000", "0.995"]
        depends_on:
            - message-service
        volumes:
          - ./stats_files:/app/stats_files:rw
        stop_signal: SIGINT
