version: "3.9"
services:
    mock-database:
        image: saheru/grpc-benchmark
        hostname: mock-database
        ports:
            - "20001:20001"
        entrypoint:
            ["/app/launcher.sh", "${OUT_NET_DELAY}", "${OUT_NET_DELAY_VAR}", "${OUT_NET_DELAY_CORR}", "taskset --cpu-list 7,9,11 /app/cmake/build/mockDatabase 0 ${W_MOCK} ${t_MOCK} ${s_MOCK}"]
        volumes:
          - ./container_files/${STATSDIR}/:/app/stats_files:rw
        stop_signal: SIGINT
        cap_add:
          - NET_ADMIN

    sanitization-service:
        image: saheru/grpc-benchmark
        hostname: sanitization-service
        ports:
            - "20003:20003"
        entrypoint:
            ["/app/launcher.sh", "${OUT_NET_DELAY}", "${OUT_NET_DELAY_VAR}", "${OUT_NET_DELAY_CORR}", "taskset --cpu-list 1,2 /app/cmake/build/sanitizationServiceAsync ${W_SANIT} ${t_SANIT} ${s_SANIT}"]
        depends_on:
            - mock-database
        volumes:
          - ./container_files/${STATSDIR}/:/app/stats_files:rw
        stop_signal: SIGINT
        cap_add:
            - NET_ADMIN

    message-service:
        image: saheru/grpc-benchmark
        hostname: message-service
        ports:
            - "20002:20002"
        entrypoint:
            ["/app/launcher.sh", "${OUT_NET_DELAY}", "${OUT_NET_DELAY_VAR}", "${OUT_NET_DELAY_CORR}", "taskset --cpu-list 3,4 /app/cmake/build/messageServiceAsync ${W_MSG} ${t_MSG} ${s_MSG}"]
        depends_on:
            - mock-database
            - sanitization-service
        volumes:
          - ./container_files/${STATSDIR}/:/app/stats_files:rw
        stop_signal: SIGINT
        cap_add:
            - NET_ADMIN

    client:
        image: saheru/grpc-benchmark
        hostname: client
        # restart: always
        entrypoint:
            ["/app/launcher.sh", "${OUT_NET_DELAY}", "${OUT_NET_DELAY_VAR}", "${OUT_NET_DELAY_CORR}", "taskset --cpu-list 5,6 /app/cmake/build/clientAsync 0 ${N} ${t_DELAY} ${s_DELAY} ${P} ${SEED}"]
        depends_on:
            - message-service
        volumes:
          - ./container_files/${STATSDIR}/:/app/stats_files:rw
        stop_signal: SIGINT
        cap_add:
            - NET_ADMIN
